version: "3"
services:
  home:
    image: hello-micro
    deploy:
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
      # restart_policy:
      #   condition: on-failure
    ports:
      - "8080:80"
    networks:
      - webnet
  foo:
    image: foo-micro
    deploy:
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
      # restart_policy:
      #   condition: on-failure
    ports:
      - "80"
    networks:
      - webnet
  bar:
    image: bar-micro
    deploy:
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
      # restart_policy:
      #   condition: on-failure
    ports:
      - "80"
    networks:
      - webnet
networks:
  webnet:
